### ISSUE TITLE
can't install this package

### ISSUE THREAD

**Issue by yafeearun** [TijmenWierenga/LaravelChargebee#10]
when i try to install a package, got the following error

Problem 1
    - Installation request for tijmen-wierenga/laravel-chargebee ^0.3.0 -> satisfiable by tijmen-wierenga/laravel-chargebee[v0.3].
    - Conclusion: remove stripe/stripe-php v6.43.1
    - Conclusion: don't install stripe/stripe-php v6.43.1
    - tijmen-wierenga/laravel-chargebee v0.3 requires stripe/stripe-php ^3.14 -> satisfiable by stripe/stripe-php[v3.14.0, v3.14.1, v3.14.2, v3.14.3, v3.15.0, v3.16.0, v3.17.0, v3.17.1, v3.18.0, v3.19.0, v3.20.0, v3.21.0, v3.22.0, v3.23.0].
    - Can only install one of: stripe/stripe-php[v3.14.0, v6.43.1].

**Comment by alexlapinete** [comment]
@yafeearun are you able to get this working?

**Comment by yafeearun** [comment]
@alexlapinete my scope is differ, so i used chargebee php package
